/*
 * MainFrame.java
 *
 * Created on 2006/06/17, 17:54
 */
package lhj.java.test;

import lhj.java.util.HexTool;

/**
 * 
 * @author sealion
 */
@SuppressWarnings("serial")
public class MainFrame extends javax.swing.JFrame {

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" �������ꂽ�R�[�h">//GEN-BEGIN:initComponents
	private void initComponents() {
		pnlCenter = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		lblGb2312 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		lblUnicode = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		lblGbk = new javax.swing.JLabel();
		lblUTF8 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		lblSjis = new javax.swing.JLabel();
		pnlTop = new javax.swing.JPanel();
		txtInput = new javax.swing.JTextField();
		lblInput = new javax.swing.JLabel();
		btnOK = new javax.swing.JButton();

		getContentPane().setLayout(null);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("MailFrame");
		setName("frmMain");
		setResizable(true);
		pnlCenter.setLayout(null);

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel2.setText("GB2312:");
		pnlCenter.add(jLabel2);
		jLabel2.setBounds(20, 20, 80, 20);

		pnlCenter.add(lblGb2312);
		lblGb2312.setBounds(105, 20, 150, 20);
		lblGb2312.getAccessibleContext().setAccessibleName("lblGb2312");

		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel4.setText("GBK:");
		pnlCenter.add(jLabel4);
		jLabel4.setBounds(20, 50, 80, 20);

		pnlCenter.add(lblUnicode);
		lblUnicode.setBounds(105, 110, 150, 20);

		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel6.setText("UTF-8:");
		pnlCenter.add(jLabel6);
		jLabel6.setBounds(20, 80, 80, 20);

		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel7.setText("UNICODE:");
		pnlCenter.add(jLabel7);
		jLabel7.setBounds(20, 110, 80, 20);

		pnlCenter.add(lblGbk);
		lblGbk.setBounds(105, 50, 150, 20);

		pnlCenter.add(lblUTF8);
		lblUTF8.setBounds(105, 80, 150, 20);

		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel8.setText("SHIFT-JIS:");
		pnlCenter.add(jLabel8);
		jLabel8.setBounds(20, 140, 80, 20);

		pnlCenter.add(lblSjis);
		lblSjis.setBounds(105, 140, 150, 20);

		getContentPane().add(pnlCenter);
		pnlCenter.setBounds(0, 40, 300, 390);

		pnlTop.setLayout(null);

		txtInput.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtInputActionPerformed(evt);
			}
		});

		pnlTop.add(txtInput);
		txtInput.setBounds(80, 10, 110, 20);

		lblInput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		lblInput.setText("Input:");
		pnlTop.add(lblInput);
		lblInput.setBounds(10, 10, 60, 20);

		btnOK.setText("OK");
		btnOK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtInputActionPerformed(evt);
			}
		});

		pnlTop.add(btnOK);
		btnOK.setBounds(200, 10, 60, 21);

		getContentPane().add(pnlTop);
		pnlTop.setBounds(0, 0, 300, 40);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 303) / 2, (screenSize.height - 254) / 2,
				303, 254);
	}

	// </editor-fold>//GEN-END:initComponents

	private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtInputActionPerformed
		String strInput = txtInput.getText();
		if (strInput.trim().equals("")) {
			return;
		}
		try {
			lblGb2312.setText(String.valueOf(HexTool
					.byteToHexCharsWithSP(strInput.getBytes("GB2312"))));
			lblGbk.setText(String.valueOf(HexTool.byteToHexCharsWithSP(strInput
					.getBytes("GBK"))));
			lblUTF8.setText(String.valueOf(HexTool
					.byteToHexCharsWithSP(strInput.getBytes("UTF-8"))));
			lblUnicode.setText(String.valueOf(HexTool
					.byteToHexCharsWithSP(strInput.getBytes("Unicode"))));
			lblSjis.setText(String.valueOf(HexTool
					.byteToHexCharsWithSP(strInput.getBytes("SHIFT-JIS"))));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_txtInputActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	// �ϐ��錾 - �ҏW�s��//GEN-BEGIN:variables
	private javax.swing.JButton btnOK;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel lblGb2312;
	private javax.swing.JLabel lblGbk;
	private javax.swing.JLabel lblInput;
	private javax.swing.JLabel lblSjis;
	private javax.swing.JLabel lblUTF8;
	private javax.swing.JLabel lblUnicode;
	private javax.swing.JPanel pnlCenter;
	private javax.swing.JPanel pnlTop;
	private javax.swing.JTextField txtInput;
	// �ϐ��錾�̏I���//GEN-END:variables

}
