// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ustcsoft.generalsolution.dmat.webui.dmat;

import com.ustcsoft.generalsolution.dmat.webui.dmat.DmatDetail;
import java.util.List;

privileged aspect DmatCalendar_Roo_JavaBean {
    
    public List<DmatDetail> DmatCalendar.getDetails() {
        return this.details;
    }
    
}
